import 'models/competitionfirstplaytwo_model.dart';import 'package:flutter/material.dart';import 'package:invovision_s_application1/core/app_export.dart';import 'package:invovision_s_application1/core/utils/validation_functions.dart';import 'package:invovision_s_application1/widgets/custom_elevated_button.dart';import 'package:invovision_s_application1/widgets/custom_icon_button.dart';import 'package:invovision_s_application1/widgets/custom_text_form_field.dart';import 'provider/competitionfirstplaytwo_provider.dart';class CompetitionfirstplaytwoDialog extends StatefulWidget {const CompetitionfirstplaytwoDialog({Key? key}) : super(key: key);

@override CompetitionfirstplaytwoDialogState createState() =>  CompetitionfirstplaytwoDialogState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => CompetitionfirstplaytwoProvider(), child: CompetitionfirstplaytwoDialog()); } 
 }
class CompetitionfirstplaytwoDialogState extends State<CompetitionfirstplaytwoDialog> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return Container(width: 299.h, padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 10.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 5.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgGroup256, height: 25.adaptSize, width: 25.adaptSize), _buildName(context), CustomImageView(imagePath: ImageConstant.imgClose, height: 14.v, width: 20.h, margin: EdgeInsets.only(left: 7.h, top: 6.v, bottom: 5.v), onTap: () {onTapImgClose(context);})]), SizedBox(height: 10.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgGroup256, height: 25.adaptSize, width: 25.adaptSize), _buildName1(context), CustomImageView(imagePath: ImageConstant.imgClose, height: 14.v, width: 20.h, margin: EdgeInsets.only(left: 7.h, top: 6.v, bottom: 5.v))]), SizedBox(height: 10.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgGroup256, height: 25.adaptSize, width: 25.adaptSize), _buildName2(context), CustomImageView(imagePath: ImageConstant.imgClose, height: 14.v, width: 20.h, margin: EdgeInsets.only(left: 7.h, top: 6.v, bottom: 5.v))]), SizedBox(height: 10.v), CustomIconButton(height: 25.adaptSize, width: 25.adaptSize, child: CustomImageView()), SizedBox(height: 20.v), Padding(padding: EdgeInsets.symmetric(horizontal: 22.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildCreate(context), _buildCancel(context)]))])); } 
/// Section Widget
Widget _buildName(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.only(left: 10.h), child: Selector<CompetitionfirstplaytwoProvider, TextEditingController?>(selector: (context, provider) => provider.nameController, builder: (context, nameController, child) {return CustomTextFormField(controller: nameController, hintText: "msg_enter_name_and_surrname".tr, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;});}))); } 
/// Section Widget
Widget _buildName1(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.only(left: 10.h), child: Selector<CompetitionfirstplaytwoProvider, TextEditingController?>(selector: (context, provider) => provider.nameController1, builder: (context, nameController1, child) {return CustomTextFormField(controller: nameController1, hintText: "msg_enter_name_and_surrname".tr, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;});}))); } 
/// Section Widget
Widget _buildName2(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.only(left: 10.h), child: Selector<CompetitionfirstplaytwoProvider, TextEditingController?>(selector: (context, provider) => provider.nameController2, builder: (context, nameController2, child) {return CustomTextFormField(controller: nameController2, hintText: "msg_enter_name_and_surrname".tr, textInputAction: TextInputAction.done, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;});}))); } 
/// Section Widget
Widget _buildCreate(BuildContext context) { return Expanded(child: CustomElevatedButton(text: "lbl_create".tr, margin: EdgeInsets.only(right: 12.h))); } 
/// Section Widget
Widget _buildCancel(BuildContext context) { return Expanded(child: CustomElevatedButton(text: "lbl_cancel".tr, margin: EdgeInsets.only(left: 12.h))); } 

/// Navigates to the previous screen.
onTapImgClose(BuildContext context) { NavigatorService.goBack(); } 
 }
