import '../competitionfirstplay_dialog/widgets/nametext_item_widget.dart';import 'models/competitionfirstplay_model.dart';import 'models/nametext_item_model.dart';import 'package:flutter/material.dart';import 'package:invovision_s_application1/core/app_export.dart';import 'provider/competitionfirstplay_provider.dart';class CompetitionfirstplayDialog extends StatefulWidget {const CompetitionfirstplayDialog({Key? key}) : super(key: key);

@override CompetitionfirstplayDialogState createState() =>  CompetitionfirstplayDialogState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => CompetitionfirstplayProvider(), child: CompetitionfirstplayDialog()); } 
 }
class CompetitionfirstplayDialogState extends State<CompetitionfirstplayDialog> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), color: appTheme.whiteA700, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder20), child: Container(height: 347.v, width: 263.h, decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 19.h), child: Column(mainAxisSize: MainAxisSize.min, children: [Text("lbl_who".tr, style: CustomTextStyles.bodySmallBlack900), SizedBox(height: 4.v), CustomImageView(imagePath: ImageConstant.imgUploadTeal500, height: 32.v, width: 69.h), SizedBox(height: 25.v), _buildNameText(context), SizedBox(height: 10.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: 130.h, padding: EdgeInsets.symmetric(vertical: 6.v), decoration: AppDecoration.fillTeal.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [CustomImageView(imagePath: ImageConstant.imgCloseYellow900, height: 30.v, width: 24.h), Padding(padding: EdgeInsets.only(top: 6.v, bottom: 5.v), child: Text("lbl_name_surrname".tr, style: CustomTextStyles.titleSmallBold))])), CustomImageView(imagePath: ImageConstant.imgClose, height: 14.v, width: 20.h, margin: EdgeInsets.only(left: 5.h, top: 14.v, bottom: 14.v))]), SizedBox(height: 25.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(margin: EdgeInsets.only(right: 12.h), padding: EdgeInsets.symmetric(horizontal: 41.h, vertical: 4.v), decoration: AppDecoration.fillTeal700.copyWith(borderRadius: BorderRadiusStyle.roundedBorder2), child: Text("lbl_next".tr, style: theme.textTheme.bodySmall)), Container(margin: EdgeInsets.only(left: 12.h), padding: EdgeInsets.symmetric(horizontal: 41.h, vertical: 4.v), decoration: AppDecoration.fillTeal700.copyWith(borderRadius: BorderRadiusStyle.roundedBorder2), child: Text("lbl_back2".tr, style: theme.textTheme.bodySmall))])]))), Align(alignment: Alignment.center, child: Container(height: 347.v, width: 263.h, decoration: BoxDecoration(color: appTheme.whiteA700.withOpacity(0.5), borderRadius: BorderRadius.circular(20.h))))]))); } 
/// Section Widget
Widget _buildNameText(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 35.h), child: Consumer<CompetitionfirstplayProvider>(builder: (context, provider, child) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 43.v, crossAxisCount: 1, mainAxisSpacing: 1.h, crossAxisSpacing: 1.h), physics: NeverScrollableScrollPhysics(), itemCount: provider.competitionfirstplayModelObj.nametextItemList.length, itemBuilder: (context, index) {NametextItemModel model = provider.competitionfirstplayModelObj.nametextItemList[index]; return NametextItemWidget(model, onTapImgCloseImage: () {onTapImgCloseImage(context);});});})); } 

/// Navigates to the previous screen.
onTapImgCloseImage(BuildContext context) { NavigatorService.goBack(); } 
 }
