import 'models/competition_model.dart';import 'package:flutter/material.dart';import 'package:invovision_s_application1/core/app_export.dart';import 'package:invovision_s_application1/widgets/custom_bottom_bar.dart';import 'package:invovision_s_application1/widgets/custom_elevated_button.dart';import 'package:invovision_s_application1/widgets/custom_text_form_field.dart';import 'provider/competition_provider.dart';class CompetitionScreen extends StatefulWidget {const CompetitionScreen({Key? key}) : super(key: key);

@override CompetitionScreenState createState() =>  CompetitionScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => CompetitionProvider(), child: CompetitionScreen()); } 
 }

// ignore_for_file: must_be_immutable
class CompetitionScreenState extends State<CompetitionScreen> {GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(child: SizedBox(height: SizeUtils.height, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Container(decoration: BoxDecoration(image: DecorationImage(image: AssetImage(ImageConstant.imgGroup629), fit: BoxFit.cover)), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildNine(context), _buildTabMenu2(context), SizedBox(height: 8.v), Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: _buildClose(context, nameSurrname: "lbl_name_surrname".tr, oneHundredNine: "lbl_113".tr, onTapClose: () {onTapClose(context);})), SizedBox(height: 10.v), Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: _buildClose(context, nameSurrname: "lbl_name_surrname".tr, oneHundredNine: "lbl_109".tr, onTapClose: () {onTapClose1(context);})), SizedBox(height: 10.v), Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: _buildClose(context, nameSurrname: "lbl_name_surrname".tr, oneHundredNine: "lbl_89".tr)), SizedBox(height: 10.v), Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: _buildClose(context, nameSurrname: "lbl_name_surrname".tr, oneHundredNine: "lbl_77".tr)), SizedBox(height: 10.v), Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: _buildClose(context, nameSurrname: "lbl_name_surrname".tr, oneHundredNine: "lbl_65".tr)), SizedBox(height: 10.v), Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: _buildClose(context, nameSurrname: "lbl_name_surrname".tr, oneHundredNine: "lbl_32".tr)), SizedBox(height: 10.v), Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: _buildClose(context, nameSurrname: "lbl_name_surrname".tr, oneHundredNine: "lbl_232".tr)), SizedBox(height: 10.v), Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: _buildClose(context, nameSurrname: "lbl_name_surrname".tr, oneHundredNine: "lbl_15".tr)), SizedBox(height: 10.v), Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: _buildClose(context, nameSurrname: "lbl_name_surrname".tr, oneHundredNine: "lbl_122".tr)), SizedBox(height: 10.v), _buildFinish(context), SizedBox(height: 62.v)]))), Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 34.h, vertical: 187.v), decoration: AppDecoration.fillWhiteA700, child: _buildDraw1(context)))])))), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
Widget _buildNine(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 12.v), decoration: AppDecoration.fillTeal700, child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgVector, height: 8.v, width: 4.h, margin: EdgeInsets.symmetric(vertical: 3.v)), Padding(padding: EdgeInsets.only(left: 5.h), child: Text("lbl_back".tr, style: theme.textTheme.bodySmall))])); } 
/// Section Widget
Widget _buildTabMenu2(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 114.h), decoration: AppDecoration.fillTeal, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(left: 8.h, top: 10.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 3.h), child: Text("lbl_table".tr.toUpperCase(), style: theme.textTheme.labelLarge)), SizedBox(height: 9.v), SizedBox(width: 32.h, child: Divider(color: appTheme.whiteA700))])), Padding(padding: EdgeInsets.only(top: 10.v, bottom: 9.v), child: Text("lbl_stage2".tr.toUpperCase(), style: theme.textTheme.labelLarge))])), SizedBox(width: 154.h, child: Divider(color: appTheme.whiteA700, indent: 122.h))]); } 
/// Section Widget
Widget _buildFinish(BuildContext context) { return CustomElevatedButton(width: 100.h, text: "lbl_finish".tr); } 
/// Section Widget
Widget _buildDraw(BuildContext context) { return CustomElevatedButton(width: 100.h, text: "lbl_draw".tr); } 
/// Section Widget
Widget _buildEnterdescriptionvalue(BuildContext context) { return Selector<CompetitionProvider, TextEditingController?>(selector: (context, provider) => provider.enterdescriptionvalueController, builder: (context, enterdescriptionvalueController, child) {return CustomTextFormField(controller: enterdescriptionvalueController, hintText: "msg_enter_description".tr, textInputAction: TextInputAction.done);}); } 
/// Section Widget
Widget _buildSave(BuildContext context) { return Expanded(child: Opacity(opacity: 0.5, child: CustomElevatedButton(text: "lbl_save".tr, margin: EdgeInsets.only(right: 12.h), buttonStyle: CustomButtonStyles.fillTealTL2))); } 
/// Section Widget
Widget _buildBack(BuildContext context) { return Expanded(child: CustomElevatedButton(text: "lbl_back2".tr, margin: EdgeInsets.only(left: 12.h))); } 
/// Section Widget
Widget _buildDraw1(BuildContext context) { return Container(margin: EdgeInsets.only(left: 1.h), padding: EdgeInsets.all(10.h), decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 115.v, width: 270.h, child: Stack(alignment: Alignment.center, children: [Padding(padding: EdgeInsets.only(left: 36.h), child: _buildVector(context, points: "lbl_points".tr, one: "lbl_1".tr)), Align(alignment: Alignment.center, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_choose_the_winner".tr, style: CustomTextStyles.bodySmallBlack900), SizedBox(height: 4.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(right: 5.h), child: _buildContrast(context, nameTeam: "lbl_name_team".tr)), Padding(padding: EdgeInsets.only(left: 5.h), child: _buildContrast(context, nameTeam: "lbl_name_team".tr))]), SizedBox(height: 9.v), Padding(padding: EdgeInsets.only(right: 37.h), child: _buildVector(context, points: "lbl_points".tr, one: "lbl_1".tr))]))])), SizedBox(height: 5.v), _buildDraw(context), SizedBox(height: 10.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_description".tr, style: CustomTextStyles.bodySmallBlack900)), SizedBox(height: 3.v), _buildEnterdescriptionvalue(context), SizedBox(height: 20.v), Padding(padding: EdgeInsets.symmetric(horizontal: 23.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildSave(context), _buildBack(context)]))])); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {}); } 
/// Common widget
Widget _buildClose(BuildContext context, {required String nameSurrname, required String oneHundredNine, Function? onTapClose, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 5.h, vertical: 6.v), decoration: AppDecoration.fillTeal.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgCloseYellow900, height: 30.v, width: 24.h, margin: EdgeInsets.only(left: 5.h), onTap: () {onTapClose!.call();}), Padding(padding: EdgeInsets.only(left: 5.h, top: 6.v, bottom: 5.v), child: Text(nameSurrname, style: CustomTextStyles.titleSmallBold.copyWith(color: appTheme.whiteA700))), Spacer(), Padding(padding: EdgeInsets.only(top: 6.v, bottom: 4.v), child: Text(oneHundredNine, style: theme.textTheme.titleSmall!.copyWith(color: appTheme.whiteA700)))])); } 
/// Common widget
Widget _buildContrast(BuildContext context, {required String nameTeam, }) { return Expanded(child: Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 6.v), decoration: AppDecoration.fillTeal.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgContrast, height: 30.v, width: 26.h), Padding(padding: EdgeInsets.only(left: 4.h, top: 6.v, bottom: 5.v), child: Text(nameTeam, style: CustomTextStyles.titleSmallBold.copyWith(color: appTheme.whiteA700)))]))); } 
/// Common widget
Widget _buildVector(BuildContext context, {required String points, required String one, }) { return Row(mainAxisAlignment: MainAxisAlignment.end, crossAxisAlignment: CrossAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgVectorTeal700, height: 2.v, width: 10.h, margin: EdgeInsets.only(top: 31.v, bottom: 11.v)), Padding(padding: EdgeInsets.only(left: 2.h), child: Column(children: [Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 4.h), child: Text(points, style: CustomTextStyles.bodySmallBlack900.copyWith(color: appTheme.black900)))), SizedBox(height: 4.v), SizedBox(height: 25.v, width: 33.h, child: Stack(alignment: Alignment.centerRight, children: [CustomImageView(imagePath: ImageConstant.imgUser, height: 25.v, width: 33.h, alignment: Alignment.center), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 13.h), child: Text(one, style: CustomTextStyles.labelLargeBlack900_1.copyWith(color: appTheme.black900))))]))])), CustomImageView(imagePath: ImageConstant.imgPlus, height: 10.adaptSize, width: 10.adaptSize, margin: EdgeInsets.only(left: 1.h, top: 27.v, bottom: 7.v))]); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 

/// Navigates to the previous screen.
onTapClose1(BuildContext context) { NavigatorService.goBack(); } 
 }
